type FocusAreas = "arms" | "legs" | "core" | "yoga" | "cardio";
// 'focus areas' is not exact -- some of these target back or other areas
// but i am going to lump them together into these categories because it's easier.
// in future iterations i may expand this and make it more 'correct'
interface Exercise {
  id: number;
  name: string;
  focusAreas: FocusAreas[];
  usesPilatesRing: boolean;
  usesWeights: boolean;
  easyReps: number[];
  medReps: number[];
  hardReps: number[];
  howToURL: string;
  isTimed: boolean;
}

const data: Exercise[] = [
  {
    id: 0,
    name: "",
    focusAreas: [],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 1,
    name: "Push Ups",
    focusAreas: ["core", "arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL: "https://www.verywellfit.com/the-push-up-exercise-3120574",
    isTimed: false,
  },
  {
    id: 2,
    name: "Crunches",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL:
      "https://www.verywellfit.com/how-to-do-a-perfect-abdominal-crunch-1229513",
    isTimed: false,
  },
  {
    id: 3,
    name: "Lunges",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL:
      "https://www.verywellfit.com/how-to-lunge-variations-modifications-and-mistakes-1231320",
    isTimed: false,
  },
  {
    id: 4,
    name: "Squats",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL: "https://www.verywellfit.com/safe-squat-technique-3119136",
    isTimed: false,
  },
  {
    id: 5,
    name: "Hip Hinges",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [10],
    medReps: [11, 20],
    hardReps: [21, 30],
    howToURL: "https://www.verywellfit.com/how-to-do-a-hip-hinge-4685934",
    isTimed: false,
  },
  {
    id: 6,
    name: "Calf Raises",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [10],
    medReps: [11, 20],
    hardReps: [21, 30],
    howToURL: "https://www.verywellfit.com/how-to-do-calf-raises-4801090",
    isTimed: false,
  },
  {
    id: 7,
    name: "Mountain Climbers",
    focusAreas: ["core", "arms", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [5, 10],
    hardReps: [11, 15],
    howToURL: "https://www.verywellfit.com/mountain-climbers-exercise-3966947",
    isTimed: false,
  },
  {
    id: 8,
    name: "Leg Lifts",
    focusAreas: ["core", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL: "https://www.wikihow.com/Do-Leg-Lifts",
    isTimed: false,
  },
  {
    id: 9,
    name: "Knee Pull-Ins",
    focusAreas: ["legs", "core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL: "https://adashofmacros.com/leg-pull-ins-core-exercise/",
    isTimed: false,
  },
  {
    id: 10,
    name: "Kicks",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [5, 10],
    hardReps: [11, 15],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 11,
    name: "Glute Bridges",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL: "https://blog.nasm.org/how-to-do-a-glute-bridge",
    isTimed: false,
  },
  {
    id: 12,
    name: "Jumping Jacks",
    focusAreas: ["cardio"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [10],
    medReps: [11, 20],
    hardReps: [20, 30],
    howToURL:
      "https://www.nytimes.com/guides/well/activity/how-to-do-a-jumping-jack",
    isTimed: false,
  },
  {
    id: 13,
    name: "Bicycle Crunches",
    focusAreas: ["core", "cardio"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [6, 10],
    hardReps: [11, 15],
    howToURL: "https://www.verywellfit.com/bicycle-crunch-exercise-3120058",
    isTimed: false,
  },
  {
    id: 14,
    name: "Tricep Dips",
    focusAreas: ["arms", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [5],
    medReps: [5, 10],
    hardReps: [11, 15],
    howToURL:
      "https://www.verywellfit.com/the-chair-dip-triceps-exercise-3120734",
    isTimed: false,
  },
  {
    id: 15,
    name: "Wall Sit",
    focusAreas: ["core", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [10],
    medReps: [20],
    hardReps: [30],
    howToURL: "https://www.verywellfit.com/the-wall-sit-quad-exercise-3120741",
    isTimed: true,
  },
  {
    id: 16,
    name: "Plank",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [10],
    medReps: [20],
    hardReps: [30],
    howToURL: "https://www.verywellfit.com/the-plank-exercise-3120068",
    isTimed: true,
  },
  {
    id: 17,
    name: "Chair Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 18,
    name: "Warrior I Pose",
    focusAreas: [],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 19,
    name: "Fan Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 20,
    name: "Warrior II Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 21,
    name: "Revolved Crescent Lunge Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 22,
    name: "Warrior III Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 23,
    name: "Hinge Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 24,
    name: "Hinge Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 25,
    name: "Standing Forward Fold",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 26,
    name: "Boat Pose",
    focusAreas: ["yoga"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 27,
    name: "Knee-to-Chest",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 28,
    name: "Standing Twist",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 29,
    name: "Plank",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 30,
    name: "Overhead Bend",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 31,
    name: "Open & Close Leg Raise",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 32,
    name: "Overhead Hip Shake",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 33,
    name: "Seated Forward Press",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 34,
    name: "Overhead Lunge Twist",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 35,
    name: "Leg Raise",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 36,
    name: "Flutter Kick",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 37,
    name: "Pendulum Bend",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 38,
    name: "Leg Scissors",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 39,
    name: "Russian Twist",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 40,
    name: "Overhead Side Bend",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 41,
    name: "Seated Ring Raise",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 42,
    name: "Squat",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 43,
    name: "Knee Lift",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 44,
    name: "Thigh Press",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 45,
    name: "Wide Squat",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 46,
    name: "Hip Lift",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 47,
    name: "Ring Raise Combo",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 48,
    name: "Overhead Squat",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 49,
    name: "Mountain Climber",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 50,
    name: "Side Step",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 51,
    name: "Knee-Lift Combo",
    focusAreas: [],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 52,
    name: "Overhead Press",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 53,
    name: "Front Press",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 54,
    name: "Bow Pull",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 55,
    name: "Overhead Arm Twist",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 56,
    name: "Overhead Arm Spin",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 57,
    name: "Shoulder Press",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 58,
    name: "Tricep Kickback",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 59,
    name: "Back Press",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 60,
    name: "Weighted Squat",
    focusAreas: ["legs", "arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
  {
    id: 61,
    name: "Weighted Tricep Kickback",
    focusAreas: ["arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    howToURL: "",
    isTimed: false,
  },
];

export default data;
