type FocusAreas = "arms" | "legs" | "core" | "yoga" | "cardio";
interface Exercise {
  id: number;
  name: string;
  focusAreas: FocusAreas[];
  usesPilatesRing: boolean;
  usesWeights: boolean;
  easyReps: number[];
  medReps: number[];
  hardReps: number[];
  isTimed: boolean;
}

const data: Exercise[] = [
  {
    id: 0,
    name: "",
    focusAreas: [],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 1,
    name: "Push Ups",
    focusAreas: ["core", "arms"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 2,
    name: "Crunches",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 3,
    name: "Lunges",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 4,
    name: "Squats",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 5,
    name: "Hip Hinges",
    focusAreas: ["core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 6,
    name: "Knee Raises",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 7,
    name: "Mountain Climbers",
    focusAreas: ["core", "arms", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 8,
    name: "Leg Lifts",
    focusAreas: ["core", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 9,
    name: "Knee Pull-Ins",
    focusAreas: ["legs", "core"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 10,
    name: "Kicks",
    focusAreas: ["legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 11,
    name: "Glute Bridges",
    focusAreas: [],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 12,
    name: "Jumping Jacks",
    focusAreas: ["cardio"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 13,
    name: "Bicycle Crunches",
    focusAreas: ["core", "cardio"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 14,
    name: "Tricep Dips",
    focusAreas: ["arms", "legs"],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
  {
    id: 15,
    name: "Wall Sit",
    focusAreas: [],
    usesPilatesRing: false,
    usesWeights: false,
    easyReps: [],
    medReps: [],
    hardReps: [],
    isTimed: false,
  },
];

export default data;
